#!/usr/bin/env -S uv run --script
# /// script
# requires-python = ">=3.11"
# dependencies = [
#     "pydantic-ai[openai,anthropic]>=0.2",
#     "opentelemetry-sdk>=1.20",
#     "opentelemetry-exporter-otlp-proto-http>=1.20",
#     "opentelemetry-instrumentation>=0.41b0",
#     "logfire[pydantic]>=2.0",
#     "httpx",
# ]
# ///
"""
Demo agent that generates traces for traceview.

Usage:
    # Start traceview first
    cargo run -- --port 6969

    # Then run this script
    uv run scripts/demo_agent.py

    # Or with a custom prompt
    uv run scripts/demo_agent.py "What's the weather in Tokyo and calculate 15% tip on $85"
"""

import sys
import random
import asyncio
from datetime import datetime

# Configure OpenTelemetry BEFORE importing pydantic_ai
from opentelemetry import trace
from opentelemetry.sdk.trace import TracerProvider
from opentelemetry.sdk.trace.export import BatchSpanProcessor
from opentelemetry.exporter.otlp.proto.http.trace_exporter import OTLPSpanExporter
from opentelemetry.sdk.resources import Resource

# Set up OTLP exporter pointing to traceview
# Note: service.instance.id is auto-generated by OTEL SDK and used by traceview
# to group all spans from this process invocation together
resource = Resource.create({
    "service.name": "demo-agent",
    "service.version": "1.0.0",
})

provider = TracerProvider(resource=resource)
exporter = OTLPSpanExporter(
    endpoint="http://localhost:6969/v1/traces",
    timeout=10,
)
provider.add_span_processor(BatchSpanProcessor(exporter))
trace.set_tracer_provider(provider)

# Now import pydantic_ai (it will pick up our tracer)
from pydantic_ai import Agent, RunContext

# Try to configure logfire for pydantic-ai instrumentation
try:
    import logfire
    logfire.configure(
        send_to_logfire=False,  # Don't send to logfire cloud
        additional_span_processors=[BatchSpanProcessor(exporter)],
    )
    logfire.instrument_pydantic_ai()
    print("✓ Logfire instrumentation enabled")
except Exception as e:
    print(f"⚠ Logfire instrumentation not available: {e}")


# =============================================================================
# Tools
# =============================================================================

async def get_weather(_ctx: RunContext[None], city: str) -> str:
    """Get the current weather for a city."""
    # Simulate API call delay
    await asyncio.sleep(0.3)

    # Fake weather data
    conditions = ["sunny", "cloudy", "rainy", "partly cloudy", "windy"]
    temp = random.randint(45, 95)
    condition = random.choice(conditions)

    return f"Weather in {city}: {temp}°F, {condition}"


async def calculate_tip(_ctx: RunContext[None], bill_amount: float, tip_percent: float) -> str:
    """Calculate the tip amount for a bill."""
    tip = bill_amount * (tip_percent / 100)
    total = bill_amount + tip
    return f"Bill: ${bill_amount:.2f}, Tip ({tip_percent}%): ${tip:.2f}, Total: ${total:.2f}"


async def search_web(_ctx: RunContext[None], query: str) -> str:
    """Search the web for information."""
    await asyncio.sleep(0.5)

    # Fake search results
    results = [
        f"Found information about '{query}': This is a simulated search result.",
        f"Related to '{query}': Additional context and details here.",
        f"Top result for '{query}': Comprehensive overview of the topic.",
    ]
    return "\n".join(results)


async def get_current_time(_ctx: RunContext[None], timezone: str = "UTC") -> str:
    """Get the current time in a specific timezone."""
    now = datetime.now()
    return f"Current time ({timezone}): {now.strftime('%Y-%m-%d %H:%M:%S')}"


async def do_math(_ctx: RunContext[None], expression: str) -> str:
    """Evaluate a mathematical expression safely."""
    try:
        # Very basic safe eval for demo purposes
        allowed = set("0123456789+-*/.() ")
        if not all(c in allowed for c in expression):
            return f"Error: Invalid characters in expression"
        result = eval(expression)  # Safe for demo with character filter
        return f"{expression} = {result}"
    except Exception as e:
        return f"Error evaluating '{expression}': {e}"


# =============================================================================
# Agent
# =============================================================================

# Create agent with tools
agent = Agent(
    # Use Claude for extended thinking support, fallback to GPT-4
    "anthropic:claude-sonnet-4-20250514",
    system_prompt="""You are a helpful assistant with access to various tools.

When asked questions:
1. Think through the problem step by step
2. Use the appropriate tools to gather information
3. Combine the results into a helpful response

Available tools:
- get_weather: Get weather for any city
- calculate_tip: Calculate tip on a bill
- search_web: Search for information
- get_current_time: Get current time
- do_math: Evaluate math expressions

Be thorough and use multiple tools when appropriate.""",
    tools=[get_weather, calculate_tip, search_web, get_current_time, do_math],
)


# =============================================================================
# Main
# =============================================================================

async def run_demo(prompt: str) -> None:
    """Run the demo agent with the given prompt."""
    print(f"\n{'='*60}")
    print(f"User: {prompt}")
    print('='*60)

    try:
        result = await agent.run(prompt)
        print(f"\nAssistant: {result.output}")
        print(f"\n📊 Usage: {result.usage()}")
    except Exception as e:
        print(f"\n❌ Error: {e}")
        raise


async def main() -> None:
    """Main entry point."""
    # Default prompts that exercise different tools
    default_prompts = [
        "What's the weather like in San Francisco and New York? Also, what time is it?",
        "I had dinner for $127.50. Calculate a 20% tip and also a 15% tip so I can compare.",
        "Search for information about OpenTelemetry and tell me about distributed tracing.",
        "Calculate these: 15 * 24, 1000 / 8, and (50 + 30) * 2",
    ]

    if len(sys.argv) > 1:
        # Use command line argument as prompt
        prompt = " ".join(sys.argv[1:])
        await run_demo(prompt)
    else:
        # Run all default prompts
        print("\n🚀 Running demo agent with multiple prompts...")
        print("   Traces will be sent to http://localhost:6969")
        print("   View them at http://localhost:6969/\n")

        for prompt in default_prompts:
            await run_demo(prompt)
            print("\n" + "-"*60 + "\n")
            await asyncio.sleep(1)  # Small delay between runs

    # Force flush traces
    provider.force_flush()
    print("\n✅ Traces exported to traceview!")
    print("   View at: http://localhost:6969/")


if __name__ == "__main__":
    asyncio.run(main())
